name: Infrastructure Tests
on: push

jobs:
  opentofu_test:
    name: "Run OpenTofu tests"
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          # Ici, on utilise le secret TEST_ROLE_ARN que tu as créé sur GitHub
          role-to-assume: ${{ secrets.TEST_ROLE_ARN }}
          role-session-name: tests-${{ github.run_number }}-${{ github.actor }}
          aws-region: us-east-2

      - uses: opentofu/setup-opentofu@v1

      - name: Tofu Test
        env:
          # Cette variable permet de créer une Lambda avec un nom unique
          TF_VAR_name: lambda-sample-${{ github.run_id }}
        working-directory: td5/scripts/tofu/live/lambda-sample
        run: |
          tofu init -backend=false -input=false
          tofu test -verbose
